!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      pitch: 0.0
      roll: -1.570795
      source_frame: base_footprint
      state: true
      target_frame: camera_color_optical_frame
      type: ''
      x: -0.2
      y: 0.29
      yaw: -2.05
      z: 1.12
    state: []
  pitch: 0.0
  roll: -1.570795
  source_frame: base_footprint
  target_frame: camera_color_optical_frame
  x: -0.2
  y: 0.29
  yaw: -2.05
  z: 1.12
state: []
